travis:
  secure:
    BINSTAR_TOKEN: So+vPAXp3h1NnnVAljbrgFB1g6BcmyA+Ip6PQGoSqO41KA/rJV9Xknr0s/MnIRQ2gQ2U7GHwkhUmXSjPtL2AhDAnW9KqNtL9MWrCeV+IT80eVhXEmZBeJHYtT2WNbylFRTBHUyGl0qNDPZ/3OdLmo//5/geinEnq5mh1qNurSAiebl0K4cGUvC49IqAxUUaC2DaVVl5vjzuaf2E72bGlUBXgVkNfiN8CCukosPPork1zJpe7Rc4pf2XOsxeMqlYvV96Xn43yJntzufpuOuFG0nK1b/BKLIDNQhXrL7WnJudr531P7tTq8s9zbtCZ9m8ARw2iGTZ2P2VFWpC3lJRoxxjY+t//rsbJw7UzhMM04Dj0meyuJfgryqTs3DZpegM7yNvJbaHFGmyE/lyhnWBOYLGolIafGFtn52KD/nZ4r1UkhiqdsgT10ZeN7MWMjnpsSWkHXaBUOpeHl/Wujdhi/4RDetw3j8jqKddAVVmYENd77tJOHUFvv5Z/sCIVYkeCpsAXw+rJHBqTQaBvGrgR1Q/XYPKJmknemVBJcM00noifihpV3YGqb15RmKEkn5ykOToiS1n/gZyrIxIXuSLiJ+avvciGZC7RL/vjYwcaL/n/Xfw1o53BEF61gAFDQUrampcVHt9x0z356/JSMfd7+wOs5aeMo3iSoaooSmKbXYM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
